# Generated by Django 5.2.11 on 2026-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(max_length=100)),
                ('mod_orden', models.IntegerField(default=0)),
                ('mod_icono', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modulos',
                'ordering': ['mod_orden'],
            },
        ),
    ]
