# Generated by Django 5.2.11 on 2026-05-26 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(max_length=100)),
                ('mod_orden', models.IntegerField(default=0)),
                ('mod_icono', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modulos',
                'ordering': ['mod_orden'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_apellido_pat', models.CharField(max_length=100)),
                ('cli_apellido_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cli_direccion', models.TextField(blank=True, null=True)),
                ('cli_ruta_ine', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menores', to='api.cliente')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('expcli_id', models.AutoField(primary_key=True, serialize=False)),
                ('expcli_tipo', models.CharField(choices=[('historia_general', 'Historia Clínica General'), ('historia_dental', 'Historia Clínica Dental'), ('consent_extrac', 'Consentimiento - Extracción'), ('consent_operatoria', 'Consentimiento - Operatoria Dental'), ('consent_ortodoncia', 'Consentimiento - Ortodoncia'), ('consent_protesis_fija', 'Consentimiento - Prótesis Fija'), ('consent_protesis_rem', 'Consentimiento - Prótesis Removible'), ('consent_aclar', 'Consentimiento - Aclaramiento Dental'), ('historia_endod', 'Historia Clínica Endodoncia'), ('consent_endod', 'Consentimiento - Endodoncia'), ('endod_evolucion', 'Endodoncia Evolución')], max_length=30)),
                ('expcli_fecha', models.DateTimeField(auto_now_add=True)),
                ('expcli_datos', models.JSONField()),
                ('expcli_ruta_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('expcli_cliente', models.ForeignKey(db_column='cli_id', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='api.cliente')),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
    ]
