# Generated by Django 5.2.11 on 2026-05-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_apellido_pat', models.CharField(max_length=100)),
                ('cli_apellido_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cli_direccion', models.TextField(blank=True, null=True)),
                ('cli_ruta_ine', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menores', to='api.cliente')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteCliente',
            fields=[
                ('expcli_id', models.AutoField(primary_key=True, serialize=False)),
                ('expcli_fecha', models.DateField(auto_now_add=True)),
                ('expcli_ruta_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('expcli_cli', models.ForeignKey(db_column='cli_id', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('expcli_exp', models.ForeignKey(db_column='exp_id', on_delete=django.db.models.deletion.CASCADE, to='api.expediente')),
            ],
            options={
                'db_table': 'expedientes_clientes',
            },
        ),
    ]
